[ERROR] There is a conflict between multiple rules for assigning the same variable.
[ERROR] 
[ERROR] This value is available because this justification is true:
[ERROR]   --> test_scope/scope.catala
[ERROR]    | 
[ERROR] 13 |   def b [ not c ] := 1337
[ERROR]    |           ^^^^^
[ERROR] 
[ERROR] This value is available because this justification is true:
[ERROR]   --> test_scope/scope.catala
[ERROR]    | 
[ERROR] 14 |   def b [ not c ] := 0
[ERROR]    |           ^^^^^
